FROM alpine:3.21

ARG TARGETPLATFORM

RUN apk add --no-cache ca-certificates tzdata python3 py3-requests

COPY $TARGETPLATFORM/picoclaw /usr/local/bin/picoclaw

ENTRYPOINT ["picoclaw"]
CMD ["gateway"]
